#ifndef OG_LIMITS_H
#define OG_LIMITS_H

//Limits
#define MAX_FRAMES_IN_FLIGHT 2
#define MAX_SWAPCHAIN_IMAGES 3
#define MAX_THREADS 32
#define MAX_JOBS 256
#define STRING_ARENA_CAPACITY MEGABYTES(32)
#define MAX_STRING_COUNT 32768U // we can intern up to 32768 unique strings
#define MAIN_SCRATCH_ARENA_CAPACITY GIGABYTES(1)
#define WORKER_SCRATCH_ARENA_CAPACITY MEGABYTES(32)
#define MAIN_PERMANENT_ARENA_CAPACITY GIGABYTES(1)
#define WORKER_PERMANENT_ARENA_CAPACITY MEGABYTES(32)
#define MAX_VERTICES (4U * 1024U * 1024U)
#define MAX_INDICES (32U * 1024U * 1024U)
#define MAX_MESHES (2U * 1024U)
#define MAX_TEXTURES (1U * 1024U)
#define MAX_MATERIALS (1U * 1024U)
#define MAX_RESOURCES (16U * 1024U)
#define MAX_MESH_DRAWS (8U * 1024U)
#define MAX_ANIMATIONS (1U * 1024U)
#define MAX_SHADERS (32U)
#endif
